### ISSUE TITLE
build on linux. list of dependencies

### ISSUE THREAD

**Issue by sl1pkn07** [mhils/flysky-updater#1]
what is the dependencies for build on linux?

greetings

**Comment by sl1pkn07** [comment]
ok. I found it:

go
go-serial
go-kingpin.v2
go-pb

optional for check:

go-color
go-go-colorable
go-pb.v1
go-assert

little question: the COM port in linux is? ttyACMx or USBx?

**Comment by mhils** [comment]
I'm just using go-serial for this, so it needs to be whatever they expect: https://github.com/jacobsa/go-serial

**Comment by mhils** [comment]
Also, for the dependencies I believe a simple `go get` would have been sufficient?
(You could also just use the binary from the release page)

**Comment by sl1pkn07** [comment]
python build.py show the missing dependencies (as warning message), right. but is my first time working with go, i don't know how download/install the dependencies.

thanks of the archlinux (my distro) go package guidelines (https://wiki.archlinux.org/index.php/Go_package_guidelines) i can manage install/build the dependencies, and the list of depends/check(test) is posted avobe

greetings

**Comment by sl1pkn07** [comment]
mmm, python build.py say:

```
└───╼  python build.py 
flysky_updater.go:9:2: cannot find package "github.com/cheggaaa/pb" in any of:
        /usr/lib/go/src/github.com/cheggaaa/pb (from $GOROOT)
        ($GOPATH not set)
flysky_updater.go:10:2: cannot find package "github.com/tarm/serial" in any of:
        /usr/lib/go/src/github.com/tarm/serial (from $GOROOT)
        ($GOPATH not set)
flysky_updater.go:11:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /usr/lib/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        ($GOPATH not set)
Traceback (most recent call last):
  File "build.py", line 12, in <module>
    build("windows","amd64","flysky-updater-win64.exe")
  File "build.py", line 10, in build
    subprocess.check_call(["go", "build", "-o", filename], env = env)
  File "/usr/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-o', 'flysky-updater-win64.exe']' returned non-zero exit status 1
```

then only need https://github.com/jacobsa/go-serial?

**Comment by sl1pkn07** [comment]
ok. tested today and works without error in my arch (64 bits) with the official usb firmware updater cable

the port in linux is like: /dev/ttyUSB0 (in my case need use with sudo, but i think is avoidable with udev rules or add my user to a uucp group)

```
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/flysky-updater]|
└───╼  sudo ./flysky-updater-linux64 /dev/ttyUSB0 flyplus_beta_20_01_16.hex
[sudo] password for sl1pkn07: 
 56.00 KB / 55.92 KB [================================================================================================================================================================================================================================================================] 100.15% 11s
Upload completed.
Success!
```

greetings and thanks!
